### ISSUE TITLE
Web getting error 500 after few hours

### ISSUE THREAD

**Issue by DJIronic** [Wruczek/ts-website#158]
Hello,

I run the latest version of dev version of ts-website (updated today). And our site gets error 500 every few hours.

Deleting the cache files helps. Any idea of what does it?

**Comment by Pyroman-FEAR** [comment]
_moved to #161_

**Comment by DJIronic** [comment]
Here is the repeating line in my error log:

`[Wed Mar 25 05:29:56.905650 2020] [php7:error] [pid 20911] [client 2001:15e8:110:2f46::1:39466] PHP Fatal error:  Uncaught Exception: Cannot load cache file! (config) in /home/simoncechacek/web/life-games.cz/public_html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php:75\nStack trace:\n#0 /home/simoncechacek/web/life-games.cz/public_html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php(313): Wruczek\\PhpFileCache\\PhpFileCache->loadCacheFile()\n#1 /home/simoncechacek/web/life-games.cz/public_html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php(62): Wruczek\\PhpFileCache\\PhpFileCache->reloadFromDisc()\n#2 /home/simoncechacek/web/life-games.cz/public_html/private/php/Config.php(39): Wruczek\\PhpFileCache\\PhpFileCache->__construct()\n#3 /home/simoncechacek/web/life-games.cz/public_html/private/php/Utils/SingletonTait.php(16): Wruczek\\TSWebsite\\Config->__construct()\n#4 /home/simoncechacek/web/life-games.cz/public_html/private/php/Utils/SingletonTait.php(26): Wruczek\\TSWebsite\\Config::Instance()\n#5 /home/simoncechacek/web/life-games.cz/public_html/private/php/Utils/DatabaseUtils.php(21): Wruczek\\TSWebsit in /home/simoncechacek/web/life-games.cz/public_html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php on line 75`

**Comment by Wruczek** [comment]
The cache problem is known, but so far I have no solution for it. 
@Pyroman-FEAR Something's wrong with languages. What language are you using? Please open a separate issue.

**Comment by DJIronic** [comment]
Well, I created a CRON record in my linux OS to remove the cache files every 15 minutes. Its not a fix, but it works for now.

**Comment by Wruczek** [comment]
You could also fully disable caching, but I don't recommend it.

**Comment by Wruczek** [comment]
Will leave this as open until I find a fix for this, its been going for a while.

**Comment by Pyroman-FEAR** [comment]
New issue is open #161  @Wruczek
