### ISSUE TITLE
Fatal error (PHP 8 support)

### ISSUE THREAD

**Issue by lx261** [Wruczek/ts-website#184]
```
Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /home/container/webroot/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php:129 Stack trace: 
#0 [internal function]: array_merge() 
#1 /home/container/webroot/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php(129): call_user_func_array() 
#2 /home/container/webroot/private/vendor/latte/latte/src/Latte/Engine.php(117): Latte\Compiler->compile() 
#3 /home/container/webroot/private/vendor/latte/latte/src/Latte/Engine.php(186): Latte\Engine->compile() 
#4 /home/container/webroot/private/vendor/latte/latte/src/Latte/Engine.php(93): Latte\Engine->loadTemplate() 
#5 /home/container/webroot/private/vendor/latte/latte/src/Latte/Engine.php(80): Latte\Engine->createTemplate() 
#6 /home/container/webroot/installer/pages/2.php(229): Latte\Engine->renderToString()
#7 /home/container/webroot/installer/pages/2.php(29): checkRequirements()
#8 /home/container/webroot/installer/index.php(28): require('...')
#9 {main} thrown in /home/container/webroot/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php on line 129
```

**Comment by Wruczek** [comment]
What's your PHP version?

**Comment by lx261** [comment]
8.0

**Comment by xopez** [comment]
> 8.0

There was a breaking change in PHP 8.
ts-website doesn't work with PHP 8 yet and there are more problems with PHP 8 as this.
You should downgrade to PHP 7.4. With this version it works very well.
Another way is to upgrade the libaries correctly.
But you have to fix what you break.

I already asked for a new release to support PHP 8 with current libaries. But this is another topic.

**Comment by lx261** [comment]
okay

**Comment by Albirew** [comment]
suggestion: this thread should be renamed "PHP 8.0 support" and be used to track changes and PR for PHP8.0 support of ts-website

**Comment by Wruczek** [comment]
We need to wait for TeamSpeak 3 PHP Framework to release a new version with https://git.io/JKlRx merged, then we will support PHP 8. Until then, TS-website 2.0.6 was released with PHP 8 marked as unsupported in installer.
